name: python app template

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  python-pipeline:
    secrets: inherit
    uses: LuisMiguelLara2106/devops-actions-ms-templates/.github/workflows/template.yml@master
